<?php
namespace App\Traits;

use App\Models\ActivityLog;

trait ActivityTrait
{
    protected static function booted()
    {
        if (auth()->check()) {
            parent::boot(); // TODO: Change the autogenerated stub
            static::created(function ($model) {
                $model->activity_log()->create([
                    'user_id' => auth()->user()->id,
                    'message' => 'Created',
                    'log' => $model
                ]);
            });

            static::updated(function ($model) {
                $model->activity_log()->create([
                    'user_id' => auth()->user()->id,
                    'message' => 'Updated',
                    'log' => $model
                ]);
            });
        }
    }

    public function activity_log()
    {
        return $this->morphMany(ActivityLog::class, 'activity');
    }
}